// <auto-generated />
using System;
using HataBildirimSistemi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HataBildirimSistemi.Migrations
{
    [DbContext(typeof(HataBildirimModelMvcContext))]
    partial class HataBildirimModelMvcContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HataBildirimSistemi.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AKullaniciAd")
                        .HasColumnName("AKullaniciAd")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("ASifre")
                        .HasColumnName("ASifre")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("BirimId")
                        .HasColumnType("int");

                    b.Property<string>("Soyad")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("TelNo")
                        .HasColumnType("char(11)")
                        .IsFixedLength(true)
                        .HasMaxLength(11)
                        .IsUnicode(false);

                    b.Property<int?>("YetkiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BirimId");

                    b.HasIndex("YetkiId");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("HataBildirimSistemi.Models.ArızaBildirim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(350)")
                        .HasMaxLength(350);

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("ArizaTurId")
                        .HasColumnType("int");

                    b.Property<int?>("BirimId")
                        .HasColumnType("int");

                    b.Property<string>("DosyaYolu")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<int?>("DurumId")
                        .HasColumnType("int");

                    b.Property<string>("KullaniciAd")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("Tarih")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("ArizaTurId");

                    b.HasIndex("BirimId");

                    b.HasIndex("DurumId");

                    b.ToTable("ArızaBildirim");
                });

            modelBuilder.Entity("HataBildirimSistemi.Models.ArızaTur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("ArızaTur");
                });

            modelBuilder.Entity("HataBildirimSistemi.Models.Birim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Birim");
                });

            modelBuilder.Entity("HataBildirimSistemi.Models.Durum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("Durum");
                });

            modelBuilder.Entity("HataBildirimSistemi.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("BirimId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("KKullaniciAd")
                        .IsRequired()
                        .HasColumnName("KKullaniciAd")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("KSifre")
                        .IsRequired()
                        .HasColumnName("KSifre")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("TelNo")
                        .IsRequired()
                        .HasColumnType("char(11)")
                        .IsFixedLength(true)
                        .HasMaxLength(11)
                        .IsUnicode(false);

                    b.Property<int?>("YetkiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BirimId");

                    b.HasIndex("YetkiId");

                    b.ToTable("Kullanici");
                });

            modelBuilder.Entity("HataBildirimSistemi.Models.Yetki", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Yetki");
                });

            modelBuilder.Entity("HataBildirimSistemi.Models.YetkiliServis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("ArizaTurId")
                        .HasColumnType("int");

                    b.Property<string>("Mail")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Soyad")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("TelNo")
                        .HasColumnType("char(11)")
                        .IsFixedLength(true)
                        .HasMaxLength(11)
                        .IsUnicode(false);

                    b.Property<string>("YKullaniciAd")
                        .HasColumnName("YKullaniciAd")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("YSifre")
                        .HasColumnName("YSifre")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<int?>("YetkiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArizaTurId");

                    b.HasIndex("YetkiId");

                    b.ToTable("YetkiliServis");
                });

            modelBuilder.Entity("HataBildirimSistemi.Models.Admin", b =>
                {
                    b.HasOne("HataBildirimSistemi.Models.Birim", "Birim")
                        .WithMany("Admin")
                        .HasForeignKey("BirimId")
                        .HasConstraintName("FK_Admin_Birim");

                    b.HasOne("HataBildirimSistemi.Models.Yetki", "Yetki")
                        .WithMany("Admin")
                        .HasForeignKey("YetkiId")
                        .HasConstraintName("FK_Admin_Yetki");
                });

            modelBuilder.Entity("HataBildirimSistemi.Models.ArızaBildirim", b =>
                {
                    b.HasOne("HataBildirimSistemi.Models.ArızaTur", "ArızaTur")
                        .WithMany("ArızaBildirim")
                        .HasForeignKey("ArizaTurId")
                        .HasConstraintName("FK_ArızaBildirim_ArızaTur");

                    b.HasOne("HataBildirimSistemi.Models.Birim", "Birim")
                        .WithMany("ArızaBildirim")
                        .HasForeignKey("BirimId")
                        .HasConstraintName("FK_ArızaBildirim_Birim");

                    b.HasOne("HataBildirimSistemi.Models.Durum", "Durum")
                        .WithMany("ArızaBildirim")
                        .HasForeignKey("DurumId");
                });

            modelBuilder.Entity("HataBildirimSistemi.Models.Kullanici", b =>
                {
                    b.HasOne("HataBildirimSistemi.Models.Birim", "Birim")
                        .WithMany("Kullanici")
                        .HasForeignKey("BirimId")
                        .HasConstraintName("FK_Kullanici_Birim")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HataBildirimSistemi.Models.Yetki", "Yetki")
                        .WithMany("Kullanici")
                        .HasForeignKey("YetkiId")
                        .HasConstraintName("FK_Kullanici_Yetki");
                });

            modelBuilder.Entity("HataBildirimSistemi.Models.YetkiliServis", b =>
                {
                    b.HasOne("HataBildirimSistemi.Models.ArızaTur", "ArızaTur")
                        .WithMany("YetkiliServis")
                        .HasForeignKey("ArizaTurId")
                        .HasConstraintName("FK_YetkiliServis_ArızaTur");

                    b.HasOne("HataBildirimSistemi.Models.Yetki", "Yetki")
                        .WithMany("YetkiliServis")
                        .HasForeignKey("YetkiId")
                        .HasConstraintName("FK_YetkiliServis_Yetki");
                });
#pragma warning restore 612, 618
        }
    }
}
