//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HataBildirimSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AltArizaTur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AltArizaTur()
        {
            this.ServisArizaTur = new HashSet<ServisArizaTur>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ArizaTurId { get; set; }
        public string Ad { get; set; }
    
        public virtual ArızaTur ArızaTur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServisArizaTur> ServisArizaTur { get; set; }
    }
}
