//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HataBildirimSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArızaBildirim
    {
        public int Id { get; set; }
        public string Ad { get; set; }
        public int ArizaTurId { get; set; }
        public string KullaniciAd { get; set; }
        public int BirimId { get; set; }
        public string Aciklama { get; set; }
        public System.DateTime Tarih { get; set; }
        public string DosyaYolu { get; set; }
        public int DurumId { get; set; }
        public Nullable<int> BinaId { get; set; }
        public Nullable<bool> Oncelik { get; set; }
        public Nullable<byte> SıraNo { get; set; }
        public Nullable<int> KullaniciId { get; set; }
        public Nullable<int> AltArizaTurId { get; set; }
    
        public virtual AltArizaTur AltArizaTur { get; set; }
        public virtual ArızaTur ArızaTur { get; set; }
        public virtual Bina Bina { get; set; }
        public virtual Birim Birim { get; set; }
        public virtual Durum Durum { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        public IEnumerable<AltArizaTur> AltArizaTurleri { get; set; }
        public IEnumerable<Kullanici> Kullanicilar { get; set; }
    }
}
