//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HataBildirimSistemi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Admin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bina()
        {
            this.ArızaBildirim = new HashSet<ArızaBildirim>();
        }
    
        public int Id { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string TelNo { get; set; }
        public Nullable<int> BirimId { get; set; }
        public string AKullaniciAd { get; set; }

        [Required]
        [StringLength(20, MinimumLength = 6, ErrorMessage = "Şifre 6 ile 20 karakter arasında olmalıdır.")]
        public string ASifre { get; set; }
        public Nullable<int> YetkiId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArızaBildirim> ArızaBildirim { get; set; }
    }
}
