//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HataBildirimSistemi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HataBildirimModelMvcEntities3 : DbContext
    {
        public HataBildirimModelMvcEntities3()
            : base("name=HataBildirimModelMvcEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<AltArizaTur> AltArizaTur { get; set; }
        public virtual DbSet<AltBirim> AltBirim { get; set; }
        public virtual DbSet<ArızaBildirim> ArızaBildirim { get; set; }
        public virtual DbSet<ArızaTur> ArızaTur { get; set; }
        public virtual DbSet<Bina> Bina { get; set; }
        public virtual DbSet<Birim> Birim { get; set; }
        public virtual DbSet<Durum> Durum { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<ServisArizaTur> ServisArizaTur { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Yetki> Yetki { get; set; }
    }
}
