//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HataBildirimSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServisArizaTur
    {
        public int Id { get; set; }
        public int KullaniciId { get; set; }
        public int ArizaTurId { get; set; }
        public int AltArizaTurId { get; set; }
    
        public virtual AltArizaTur AltArizaTur { get; set; }
        public virtual ArızaTur ArızaTur { get; set; }
        public virtual Kullanici Kullanici { get; set; }
    }
}
