//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HataBildirimSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YetkiliServis
    {
        public int Id { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string TelNo { get; set; }
        public string Mail { get; set; }
        public string YKullaniciAd { get; set; }
        public string YSifre { get; set; }
        public Nullable<int> YetkiId { get; set; }
        public Nullable<int> ArizaTurId { get; set; }
    
        public virtual ArızaTur ArızaTur { get; set; }
        public virtual Yetki Yetki { get; set; }
    }
}
